### PR TITLE
Adding basic layout for our app, adding Bootstrap and Font Awesome.

### PR DESCRIPTION
**Pull request by macrivello**
I went ahead and created a simple layout so we can look at something a little less ugly. 

I also included Bootstrap 4 and Font Awesome (for icons mainly). 

I'm bootstrapping MainComponent instead of AppComponent. <app-root> is that selector for MainComponent, so this is the top level component now.

### CODE REVIEW

**Comment by JPautz** [comment]
Is this the same component that would be our home page component?

**Comment by JPautz** [comment]
If so is the file structure correct. 
App
-Layout
   -main component
   -navbar component

Vs

App
-Component
   -main component
   -navbar component

**Comment by JPautz** [comment]
^ Main and Navbar components are subfolders of layout and component respectively

**Comment by macrivello** [comment]
I was thinking more or less following the structure of the jhipster app. I'm open to alternatives. Heading to bed now, lets talk about it tomorrow.

**Comment by macrivello** [comment]
But @JPautz to answer your structure question, layouts could either live inside or along side of a components folder that contains our primary components like flowchart, course, etc.

**Comment by JPautz** [comment]
Ok thats sounds good. Wanted to get a sort of defined file structure in place so when we go to add components or layouts or services it's clear where to place them

**Comment by macrivello** [comment]
Ok, I'll review https://angular.io/styleguide#!#04-06 and update the commit

**Pull request merged**
